# Build
FROM ubuntu:22.04 AS base


# Install basic utilities
RUN apt update && \
    apt install -y curl wget unzip iputils-ping && \
    apt clean


RUN curl -sSL https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb -o nordvpn.deb && \
    apt install -y ./nordvpn.deb && \
    apt update && \
    apt install -y nordvpn

# Expose necessary ports for NordVPN
EXPOSE 1194/udp
EXPOSE 443/tcp
EXPOSE 500/udp
EXPOSE 4500/udp
EXPOSE 51820/udp

# Copy your custom scripts into the Docker image
# Replace `path/to/your/scripts` with the actual path to your scripts
COPY startup_script.sh /usr/local/bin/
COPY token.txt /root/

RUN chmod +x /usr/local/bin/startup_script.sh

# Expose necessary ports (adjust as needed)
# EXPOSE 8080

# Set the entrypoint to your custom script or a startup script
ENTRYPOINT ["/usr/local/bin/startup_script.sh"]

